### ISSUE TITLE
De-clutter display of token values

### ISSUE THREAD

**Issue by myrho** [graphsense/graphsense-dashboard#377]
Maybe provide another filter for token currencies

**Comment by behas** [comment]
Currently we display tx and token transfers in the same view. We need to somehow disentangle this because users are typically interested in tracing assets selectively.

Proposed solution:
- In the menu, introduce a dropdown menu allowing users to select the chain (e.g., BTC, ETH, TRON) and another child drop down menu next to it allowing the users to select the asset. For BTC and UTXO ledgers there will be just one asset; for account model ledger there might be multiple (e.g., ETH, USDC, USDT)
- The filter should apply to all property boxes and also the graph view
- In the master property box we should display all the relevant (used) chains/assets for a given address. This allows the users to trace selectively..

**Comment by behas** [comment]
Also here, I propose to take an asset-centric view and let users within a certain asset type, e.g, ETH, USDT/ETH, etc.

We should, of course, show what types of assets a certain address is involved in; probably in the property box.

**Comment by soad003** [comment]
We decided to use fiat currency for to show aggregate values like total received, balance etc. In the property boxes as well as the graph edges on the address graph. Also the edges should indicate how many asset currencies were used. When clicking on the edge the relationship property box should show the composition of assets e.g 30 % of the transferred assets between the two entities/addresses were USDT/ETH etc.

**Comment by myrho** [comment]
In order to keep the changes to users as small as possible, we solve this now by:
* Show the highest token on the edges and indicate if there are more token values
* If user switches to EUR/USD display, show aggregate fiat values
* In address/entity statistics show the fiat aggregates and add an option to show detailed token values
* In address/entity neighbor tables only show fiat aggregates.
